### PR TITLE
Commenting system phase 1

### PR DESCRIPTION
**Pull request by vleong2332**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/608)

### CODE REVIEW

**Comment by rbnswartz** [comment]
Reviewed 33 of 46 files at r1, 1 of 1 files at r2, 11 of 11 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r8, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[static/src/js/main.js, line 129 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJkCusqu1omUMaM8_y-:-KJkCusqu1omUMaM8_y0:-247048040) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/static/src/js/main.js#L129)):*
> ```JavaScript
>     });
> 
>     // Submit delete comment form when clicking on the trash icon
> ```

Is there a reason that this is in the global js instead of being something that is imported when needed?

---

*[td/receivers.py, line 61 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJkGupxJXyqiX7NHS1K:-KJkGupxJXyqiX7NHS1L:-913729124) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/receivers.py#L61)):*
> ```Python
> 
> 
> @receiver(post_save, sender=Language)
> ```

the default is set to None but there is no check for none before using properties on it. This would cause an error

---

*[td/commenting/forms.py, line 18 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJl1ipdCt3iq3BrhUO8:-KJl1ipeQTs0U6_HBkAE:-1303258955) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/forms.py#L18)):*
> ```Python
>     def process_tags(self):
>         comment = self.cleaned_data.get("comment")
>         tags = [part.replace("#", "") for part in comment.split() if part.__contains__("#")]
> ```

FYI you could have used "#" in part

---

*[td/commenting/models.py, line 29 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJl4KcMhhJacoSGtULV:-KJl4KcMhhJacoSGtULW:-352910940) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/models.py#L29)):*
> ```Python
>     @property
>     def html(self):
>         object_url = self.content_object.get_absolute_url() if hasattr(self.content_object, "get_absolute_url") else ""
> ```

So if there isn't anything to link it to we are still going to show a link? Perhaps we shouldn't provide a link if it isn't going to go where expected

---

*[td/commenting/models.py, line 62 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJl5LPJOZf-MaxddI5b:-KJl5LPJOZf-MaxddI5c:1654636880) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/models.py#L62)):*
> ```Python
>     @property
>     def hashtag(self):
>         return "".join(["#", self.tag_slug])
> ```

Is there a reason you are using join instead of "#" + self.tag_slug

---

*[td/commenting/models.py, line 82 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJl9_bxf3QMwUvNm3Yx:-KJl9_byLe0NN8eQo9Mv:-713874687) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/models.py#L82)):*
> ```Python
>             "user_id": comment.user_id,
>             "submit_date": comment.submit_date,
>             "source": mark_safe("<span class=\"mention-source\"> - mentioned in <a class=\"mention-source-link\"href=\""
> ```

Is the "-" needed?

---

*[td/commenting/management/commands/refresh_comment_tags.py, line 21 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpCwP3h2quvu-Ea12y:-KJpCwP4JhBloOciCN_Q:1302199537) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/management/commands/refresh_comment_tags.py#L21)):*
> ```Python
>             for instance in model.objects.all():
>                 try:
>                     CommentTag.objects.get_or_create(name=instance.tag_slug, slug=instance.tag_slug,
> ```

You are using a get or create but not doing anything with returned values if any. Is this intended?

---

*[td/commenting/management/commands/update_comment_tags.py, line 18 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpD8dYEPpWhdUHi1kp:-KJpD8dYEPpWhdUHi1kq:251670526) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/management/commands/update_comment_tags.py#L18)):*
> ```Python
>             for instance in model.objects.all():
>                 try:
>                     CommentTag.objects.get_or_create(name=instance.tag_slug, slug=instance.tag_slug,
> ```

Again get or create but doing nothing with the returned value. Is this intended?

---

*[td/templates/comments/list.html, line 12 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpDzjewme65ZWgjKed:-KJpDzjfXOItUUvBT3Yb:1750226198) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/templates/comments/list.html#L12)):*
> ```HTML
>       <li>
> 
>         {{ comment.comment|safe|linebreaks }}
> ```

I don't know if this is in spec but urlize would also be a good tag to throw on this. Will create actual links out of things that look like links. Would be a nice quality of life for the users if they put a url or email address in the comment.

---

*[td/templates/comments/list.html, line 30 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpEFnTvY0GwMP0oQT9:-KJpEFnUGgIpUzogb75j:1348019447) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/templates/comments/list.html#L30)):*
> ```HTML
>         </p>
> 
>         {% if not forloop.last %}
> ```

Didn't know this existed. Very cool.

---

*[td/templates/resources/country_detail.html, line 47 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpEh_rmN-m68H9hTs5:-KJpEh_rmN-m68H9hTs6:-1674838877) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/templates/resources/country_detail.html#L47)):*
> ```HTML
>                     <tbody>
>                         <tr><th class="col-md-2">Code</th><td>{{ country.code|default:"_" }}</td><tr>
>                         <tr><th>Hashtag</th><td>{{ country.hashtag|default:"-" }}</td></tr>
> ```

Do we really need to be showing the hashtag? Or is that just something for phase one?

---

*[td/templates/resources/language_detail.html, line 161 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpExZ7WS-fNMvBI6hD:-KJpExZ7WS-fNMvBI6hE:1303186177) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/ab4da08d6ebd2dbdc6e2eaf8f3201c3943c99d29/td/templates/resources/language_detail.html#L161)):*
> ```HTML
>                     {% if charter %}
>                         {% include "resources/_project_detail.html" with data=charter %}
>                         <h2>Event Count</h2>
> ```

Did you remove this because of the performance issues you were having?

---

*[td/tests/test_utils.py, line 85 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpUK0cNDQKHzQatXFO:-KJpUK0cNDQKHzQatXFP:938237079) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/test_utils.py#L85)):*
> ```Python
>         self.assertEqual(two_digit_datetime("123"), "23")
> 
>     def test_word_string(self):
> ```

so a function called two_digit_datetime is taking in a string as a valid use case? The name of the function would lead me to believe that it does something else then what it actually does. If this isn't your code or will take a while to fix don't worry about it. It could cause issues in the future though from not understanding what a function does from reading its name.

---

*[td/tests/test_utils.py, line 116 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpVLNSC-jlRt1f-wgZ:-KJpVLNSC-jlRt1f-wg_:-1091916241) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/test_utils.py#L116)):*
> ```Python
>     def test_queryset(self):
>         self.view.model = WARegion
>         WARegion.objects.get_or_create(name="Middle Earth", slug="middleearth")
> ```

These objects aren't deleted after they are used. This could cause other problems for other tests in the future possibly.

---

*[td/tests/tracking/test_models.py, line 80 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpWKOxvmGs2DnNtuBA:-KJpWKOyruS1diejWW_g:-2063937246) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/tracking/test_models.py#L80)):*
> ```Python
>         start_date = timezone.now().date()
>         end_date = timezone.now().date()
>         # WHY: If the "id" are not specified, self.model.event_set.all() only shows 1 event in the charter.
> ```

If you are using get_or_create yes that is the case (Maybe it won't since you are specifying location). Just flat out creating wouldn't have that problem. And the objects aren't cleaned up afterwards.

---

*[td/tracking/receivers.py, line 24 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpXtnh84RvVkAgIVcJ:-KJpXtnh84RvVkAgIVcK:-556193206) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tracking/receivers.py#L24)):*
> ```Python
>     # In other words, the update event form is broken.
>     #
>     # See github issue #598
> ```

Thank you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608)*

**Comment by vleong2332** [comment]
Reviewed 3 of 46 files at r1, 2 of 11 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[static/src/js/main.js, line 129 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJkCusqu1omUMaM8_y-:-KJqIbcrDNx8M_432RXs:1624767819) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/static/src/js/main.js#L129)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Is there a reason that this is in the global js instead of being something that is imported when needed?
</details>
Yes. All the JS is essentially at the "global" level, since they're going to be bundled into `site.js`

---

*[td/receivers.py, line 61 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJkGupxJXyqiX7NHS1K:-KJqQxNOYJa4WWqrDLjv:179222234) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/receivers.py#L61)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> the default is set to None but there is no check for none before using properties on it. This would cause an error
</details>
OK. Putting in the check.

---

*[td/commenting/models.py, line 29 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJl4KcMhhJacoSGtULV:-KJqR05fWCtvzPI5erzM:-1656000635) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/models.py#L29)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> So if there isn't anything to link it to we are still going to show a link? Perhaps we shouldn't provide a link if it isn't going to go where expected
</details>
OK. Setting the default to `#`, which is a standard practice.

---

*[td/commenting/models.py, line 62 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJl5LPJOZf-MaxddI5b:-KJqLJxpmoNBVsGPyQyu:-622111110) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/models.py#L62)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Is there a reason you are using join instead of "#" + self.tag_slug
</details>
`.join()` is the recommended way to concatenate a string in python. For reference: http://stackoverflow.com/questions/2133571/most-pythonic-way-to-concatenate-strings

---

*[td/commenting/models.py, line 82 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJl9_bxf3QMwUvNm3Yx:-KJqLyhYz5G4JwuqpHMR:289001994) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/models.py#L82)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Is the "-" needed?
</details>
Yes. And the white spaces too.

---

*[td/commenting/management/commands/refresh_comment_tags.py, line 21 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpCwP3h2quvu-Ea12y:-KJqMJjDdGWjNAmyWcjb:1154274658) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/management/commands/refresh_comment_tags.py#L21)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> You are using a get or create but not doing anything with returned values if any. Is this intended?
</details>
Yes. It only creates/registers the tag if there's not an existing one already.

---

*[td/commenting/management/commands/update_comment_tags.py, line 18 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpD8dYEPpWhdUHi1kp:-KJqMgFm2KszO_woV7ut:677251276) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/management/commands/update_comment_tags.py#L18)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Again get or create but doing nothing with the returned value. Is this intended?
</details>
Yes.

---

*[td/templates/comments/list.html, line 12 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpDzjewme65ZWgjKed:-KJqR7bdId1KTrrpabHt:1317299815) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/templates/comments/list.html#L12)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> I don't know if this is in spec but urlize would also be a good tag to throw on this. Will create actual links out of things that look like links. Would be a nice quality of life for the users if they put a url or email address in the comment.
</details>
OK. Good idea.

---

*[td/templates/resources/language_detail.html, line 161 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpExZ7WS-fNMvBI6hD:-KJqNGhq-ToATzlYjXwH:1305627660) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/ab4da08d6ebd2dbdc6e2eaf8f3201c3943c99d29/td/templates/resources/language_detail.html#L161)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Did you remove this because of the performance issues you were having?
</details>
No. I removed it per spec (given by Mark).

---

*[td/tests/test_utils.py, line 85 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpUK0cNDQKHzQatXFO:-KJqNgu0_KmJhcJsu-3m:1526468610) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/test_utils.py#L85)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> so a function called two_digit_datetime is taking in a string as a valid use case? The name of the function would lead me to believe that it does something else then what it actually does. If this isn't your code or will take a while to fix don't worry about it. It could cause issues in the future though from not understanding what a function does from reading its name.
</details>
The intent is to be able to pass either `int` (7) **or** number `str` ("7"). If a user decides to call `two_digit_datetime("whatever")`, which doesn't really make sense in the first place, the function won't break, it will just spew out the last two letter of the string. Do you have a suggestion for a better function name?

---

*[td/tests/test_utils.py, line 116 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpVLNSC-jlRt1f-wgZ:-KJqOpxMERrb9KyFVe-M:-582341698) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/test_utils.py#L116)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> These objects aren't deleted after they are used. This could cause other problems for other tests in the future possibly.
</details>
Why aren't they deleted? I thought they are always deleted.

---

*[td/tests/tracking/test_models.py, line 80 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpWKOxvmGs2DnNtuBA:-KJqQZIbtOrfFx411JC9:-1591325441) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/tracking/test_models.py#L80)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> If you are using get_or_create yes that is the case (Maybe it won't since you are specifying location). Just flat out creating wouldn't have that problem. And the objects aren't cleaned up afterwards.
</details>
I tried switching it to `create()` without the `id`, but it's throwing a `TransactionManagementError`. I think I'll stick with these, unless there's a good reason to change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608)*

**Comment by rbnswartz** [comment]
Review status: 48 of 52 files reviewed at latest revision, 9 unresolved discussions.

---

*[td/commenting/models.py, line 62 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJl5LPJOZf-MaxddI5b:-KJqRzm9adHLeDOp3lYS:1673613539) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/commenting/models.py#L62)):*
<details><summary><i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>
> `.join()` is the recommended way to concatenate a string in python. For reference: http://stackoverflow.com/questions/2133571/most-pythonic-way-to-concatenate-strings
</details>
But it isn't a list. If you had more then one value to concatenate then 100%. But in the case where you don't the + is roughly 10 times faster.

---

*[td/tests/test_utils.py, line 85 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpUK0cNDQKHzQatXFO:-KJqUL-vv3Q_JSEaBTYG:1766662963) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/test_utils.py#L85)):*
<details><summary><i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>
> The intent is to be able to pass either `int` (7) **or** number `str` ("7"). If a user decides to call `two_digit_datetime("whatever")`, which doesn't really make sense in the first place, the function won't break, it will just spew out the last two letter of the string. Do you have a suggestion for a better function name?
</details>
Just dropping datetime off of it would make sense as it really doesn't have anything to do with a datetime and none of the use cases have it actually consuming a datetime

---

*[td/tests/test_utils.py, line 116 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpVLNSC-jlRt1f-wgZ:-KJqVuyz73xIaK5bbOHH:-1002745892) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/test_utils.py#L116)):*
<details><summary><i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>
> Why aren't they deleted? I thought they are always deleted.
</details>
Ok I'm wrong. I thought only setUp and tearDown would do that but that isn't the case. Nevermind

---

*[td/tests/tracking/test_models.py, line 80 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpWKOxvmGs2DnNtuBA:-KJqUvOpz94KrtT9UgNv:947501934) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/tracking/test_models.py#L80)):*
<details><summary><i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>
> I tried switching it to `create()` without the `id`, but it's throwing a `TransactionManagementError`. I think I'll stick with these, unless there's a good reason to change it.
</details>
I mean it could cause you trouble in the future in some cases. But we can deal with them at that point. Just makes me a little nervous.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608)*

**Comment by rbnswartz** [comment]
Reviewed 4 of 4 files at r11.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608)*

**Comment by rbnswartz** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[td/tests/test_utils.py, line 85 \[r10\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608#-KJpUK0cNDQKHzQatXFO:-KJqeKKtw0GzkOvMEnpo:-805211409) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/6b4e736a4078b2ef26e6a6fb7fc3235a2b16ee78/td/tests/test_utils.py#L85)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Just dropping datetime off of it would make sense as it really doesn't have anything to do with a datetime and none of the use cases have it actually consuming a datetime
</details>
Needs to probably be refactored in the future but ok for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/608)*

**Pull request merged**
