### PR TITLE
Polished GL Tracking

### PR DESCRIPTION
**Pull request by vleong2332**
[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/398)

### CODE REVIEW

**Comment by phillip-hopper** [comment]
@vleong2332: What do you need help with?

**Comment by vleong2332** [comment]
@phillip-hopper: Review and approval. It's for tomorrow. The error is caused by flake8. I saw your PR for that.

**Comment by phillip-hopper** [comment]
@vleong2332: To make this easier to review, it might help if you squashed these commits into 3 -- one with the files renamed but not changed, one with the added and removed files, and another with the existing files that were changed.

**Comment by vleong2332** [comment]
New PR with some commits squashed #415

**Pull request closed without merging**
