### PR TITLE
Added partner functionality

### PR DESCRIPTION
**Pull request by rbnswartz**
Squashed changes:

Some model changes and improvements
Changes based on user feedback and usability improvements
Modify the country field to allow blank values
Security is great when you actually implement it correctly
Sane names for start and end, moved validation to form
Adhere to PEP8
Added tests
Moving everthing to one migration
Added back to list link to detail
Changes based on peer review
Added some minor form lable changes for consistency

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/453)

### CODE REVIEW

**Comment by vleong2332** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[td/gl_tracking/forms.py, line 92 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUOoAI0ddaPPZ1bbPq:-KBUOoAJ2_GguWFVFrXr:1604193150) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/gl_tracking/forms.py#L92)):*
I just noticed the 2 identical return statements. Maybe something like this will be better?
```
if partner_start is not None and partner_start > partner_end:
    raise ValidationError("...")

return partner_end
```    

---

*[td/gl_tracking/urls.py, line 24 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBURqRTPG0VxbfbzUlW:-KBURqRUIOjJJLqdF26w:1433837284) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/gl_tracking/urls.py#L24)):*
I don't know if there's real difference between [0-9] and \d, but it's an option.

---

*[td/gl_tracking/views.py, line 11 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUS9gTxbxcDJ7n4qnR:-KBUS9gTxbxcDJ7n4qnS:-752977106) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/gl_tracking/views.py#L11)):*
What's the reason `Partner' is imported on its own line? You can append it to the line below it. You can actually change `td.gl_tracking.models` to `.models` if you want. Relative import is what I heard is recommended.

---

*[td/templates/gl_tracking/partner_detail.html, line 47 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUT2YNUbz8_6HYwVKV:-KBUT2YNUbz8_6HYwVKW:1616143128) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/templates/gl_tracking/partner_detail.html#L47)):*
What are these red squares?

---

*[td/templates/gl_tracking/partner_form.html, line 11 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUTCBwKqFGxOS9Zkm8:-KBUTCBwKqFGxOS9Zkm9:837908900) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/templates/gl_tracking/partner_form.html#L11)):*
Is this title correct? `Add Language`?

---

*[td/templates/site_base.html, line 157 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUTVaIldUp0BfSqVMG:-KBUTVaIldUp0BfSqVMH:-441206228) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/templates/site_base.html#L157)):*
Could you move this to below `Translation Projects`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453)*

**Comment by rbnswartz** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[td/gl_tracking/views.py, line 11 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUS9gTxbxcDJ7n4qnR:-KBUUFlssb__upNMlqwx:1891773185) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/gl_tracking/views.py#L11)):*
Yeah probably could be cleaned up. Good catch. I'll make that change

---

*[td/templates/gl_tracking/partner_detail.html, line 47 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUT2YNUbz8_6HYwVKV:-KBUUUO56nU4ew5mOIuh:1183594413) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/templates/gl_tracking/partner_detail.html#L47)):*
I'm assuming it is complaining about the lack of a newline char. I can add one if it makes a difference to you

---

*[td/templates/gl_tracking/partner_form.html, line 11 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUTCBwKqFGxOS9Zkm8:-KBUUczkX7C8Df0WbydM:843554340) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/templates/gl_tracking/partner_form.html#L11)):*
Um no that is not. Again thanks for the catch.

---

*[td/templates/site_base.html, line 157 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUTVaIldUp0BfSqVMG:-KBUUgxTyGhr3eNj0KNE:-189512168) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/templates/site_base.html#L157)):*
Yeah I meant to do that but didn't get around to it thanks.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[td/templates/gl_tracking/partner_detail.html, line 47 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453#-KBUT2YNUbz8_6HYwVKV:-KBUUwnblRr9iP5RqnFE:666377931) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/74f2fff430ea470d98d52ac739785470e2583930/td/templates/gl_tracking/partner_detail.html#L47)):*
It doesn't to me, but I've fallen to the same pit before. Flake8 only check `.py` files. So we need to be more careful to check for compliance in the template files.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453)*

**Comment by vleong2332** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/453)*

**Pull request merged**
