### PR TITLE
Add word count as weight to Documents

### LINKED ISSUE #528: Give weights to documents in GL Tracker
## User Story
As a GL Director I wish to have an understanding of percentage done which tracks against word count done vs word count total.  

This will help balance against valuing large book (80,000 words) with smaller books (8,000 words)

The word-counts for most of these portions of text are readily-available within Door43,   (https://door43.org/word-counts)

### PR DESCRIPTION
**Pull request by vleong2332**
Resolves #528 

The progress rate for each GL is skewed because some documents are
bigger/smaller than the others. 100% completion of a 200-word document
is not the same as 100% completion of a 30,000-word document.

Word-count is added as a way to weigh these documents. Therefore, 100%
completion rate for a 30,000-word document is significantly heftier
than the one for a 200-word document. The reverse is also true.

Also refactored PhaseView and its functions while at it.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/542)

### CODE REVIEW

**Comment by rbnswartz** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[td/gl_tracking/views.py, line 184 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/542#-KFyLM6lYd5Tde1shs2_:-KFyLM6m27MyAZDvYMSq:-393333290) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/7cff0c50345c50b79272b20a1d00d9e79440271f/td/gl_tracking/views.py#L184)):*
Why are you doing this? Won't x be the region object without having search the regions for the region?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/542)*

**Comment by vleong2332** [comment]
*[td/gl_tracking/views.py, line 184 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/542#-KFyLM6lYd5Tde1shs2_:-KFyfsv-aLmhZBLRLj4t:-1380055971) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/7cff0c50345c50b79272b20a1d00d9e79440271f/td/gl_tracking/views.py#L184)):*
Because the `regions` argument is a dictionary of `{"key": some_value}`, so `x` in `lambda x:` is the string `"key"`. I probably should make that clearer through documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/542)*

**Comment by vleong2332** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[td/gl_tracking/views.py, line 184 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/542#-KFyLM6lYd5Tde1shs2_:-KFyw61CtEGs_NVVzRRc:-499146009) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/7cff0c50345c50b79272b20a1d00d9e79440271f/td/gl_tracking/views.py#L184)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/542)*

**Comment by rbnswartz** [comment]
Reviewed 1 of 1 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[td/gl_tracking/views.py, line 184 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/542#-KFyLM6lYd5Tde1shs2_:-KFz3vtfjS0obAuA7qUS:527957759) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/7cff0c50345c50b79272b20a1d00d9e79440271f/td/gl_tracking/views.py#L184)):*
I was thinking you might be able to do a key,value but I couldn't get it to work for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/542)*

**Comment by rbnswartz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/542)*

**Pull request merged**
