### PR TITLE
Vl 444 remove network

### LINKED ISSUE #444: Pull the Network field from the Event Form
No longer considered relevant.

### PR DESCRIPTION
**Pull request by vleong2332**
Resolves #444, #443, #442

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/475)

### CODE REVIEW

**Comment by phillip-hopper** [comment]
Reviewed 5 of 9 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[td/templates/tracking/event_form.html, line 251 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475#-KCHYkZ4o_6zZuMo7TQf:-KCHYkZ4o_6zZuMo7TQg:-1418005368) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/34a0b90b2a3d86d071e257b289f3dcf9f4fcd656/td/templates/tracking/event_form.html#L251)):*
It looks like `change` could be set more than once.  It may be better to use `charter.off("charter.change").on("charter.change", updatePartner);`.

---

*[td/templates/tracking/multi_charter_event_form.html, line 342 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475#-KCHaoZh7K3oHP0pTJKh:-KCHaoZisDuzsNoda-AH:1030879690) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/34a0b90b2a3d86d071e257b289f3dcf9f4fcd656/td/templates/tracking/multi_charter_event_form.html#L342)):*
This has the potential to return more than one value.

---

*[td/templates/tracking/multi_charter_event_form.html, line 345 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475#-KCHfhRs5wwXG_S_RziE:-KCHfhRt3dS4srKJTM1l:-681224521) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/34a0b90b2a3d86d071e257b289f3dcf9f4fcd656/td/templates/tracking/multi_charter_event_form.html#L345)):*
Is this logic correct if there is an error on the server?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[td/templates/tracking/event_form.html, line 251 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475#-KCHYkZ4o_6zZuMo7TQf:-KCI1wb8JFOOAG_EQ92l:-499146009) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/34a0b90b2a3d86d071e257b289f3dcf9f4fcd656/td/templates/tracking/event_form.html#L251)):*
Done.

---

*[td/templates/tracking/multi_charter_event_form.html, line 342 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475#-KCHaoZh7K3oHP0pTJKh:-KCI2GAVNDZfc4OzEK0z:-1001942287) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/34a0b90b2a3d86d071e257b289f3dcf9f4fcd656/td/templates/tracking/multi_charter_event_form.html#L342)):*
`querySelector`only returns the first matched element. There's a minuscule possibility that another `<input name="charter-lookup" ... />`is declared, which may cause the wrong element to be selected. However, that's the case of human error (like naming 2 elements with the same `id`)

---

*[td/templates/tracking/multi_charter_event_form.html, line 345 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475#-KCHfhRs5wwXG_S_RziE:-KCI3KPE6_0kaBUp3w4P:1305213900) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/34a0b90b2a3d86d071e257b289f3dcf9f4fcd656/td/templates/tracking/multi_charter_event_form.html#L345)):*
You're right. Probably should check for an error.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[td/templates/tracking/multi_charter_event_form.html, line 345 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475#-KCHfhRs5wwXG_S_RziE:-KCI4234fdEl6nf8XA1E:852603822) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/34a0b90b2a3d86d071e257b289f3dcf9f4fcd656/td/templates/tracking/multi_charter_event_form.html#L345)):*
Actually, in the case of server error, `partner.value` won't be updated, which is the expected behavior.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475)*

**Comment by phillip-hopper** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/475)*

**Pull request merged**
