### PR TITLE
Fixed a problem with the label on a date field

### PR DESCRIPTION
**Pull request by rbnswartz**
A very short minor field change based on feedback from Mark.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/470)

### CODE REVIEW

**Comment by vleong2332** [comment]
*[td/gl_tracking/forms.py, line 101 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/470#-KBrbKhpGULgH-44LHKy:-KBrbKhqkOO8o8O3BVF1:-1695669388) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/52e47590551b123ff56469f7a7a0912f2378c459/td/gl_tracking/forms.py#L101)):*
I think you had it right to put the label in the meta, since we're going to extract out the `DateField()` definition.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/470)*

**Comment by rbnswartz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[td/gl_tracking/forms.py, line 101 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/470#-KBrbKhpGULgH-44LHKy:-KBrc43pCL7zxGbJ_Q1r:-2134679430) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/52e47590551b123ff56469f7a7a0912f2378c459/td/gl_tracking/forms.py#L101)):*
Yeah that doesn't seem to work. We might have to put some more work into figuring out why but this is at least a quick fix. Since you are deriving your date field from the date field we should still be able to still do this with the new date field definition. But this was definitely not working before.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/470)*

**Comment by vleong2332** [comment]
*[td/gl_tracking/forms.py, line 101 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/470#-KBrbKhpGULgH-44LHKy:-KBre4jSsnRlnUavrr-F:-1228986237) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/52e47590551b123ff56469f7a7a0912f2378c459/td/gl_tracking/forms.py#L101)):*
It could be because the info in `meta` is overridden by the definition in `__init__()`. This is fine then. We'll make `BSDateField` more robust.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/470)*

**Comment by vleong2332** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/470)*

**Comment by rbnswartz** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[td/gl_tracking/forms.py, line 101 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/470#-KBrbKhpGULgH-44LHKy:-KBri8gIpFATa8udF1B8:-785938661) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/52e47590551b123ff56469f7a7a0912f2378c459/td/gl_tracking/forms.py#L101)):*
I would guess it is actually a problem with the ModelForm not setting the label correctly on date fields.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/470)*

**Pull request merged**
