### PR TITLE
Fixed the check for lc to check for country

### LINKED ISSUE #472: Cannot see detail for languages without country

### PR DESCRIPTION
**Pull request by vleong2332**
Resolves #472 

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/473)

### CODE REVIEW

**Comment by rbnswartz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[td/templates/resources/language_detail.html, line 105 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/473#-KBsCwJRpBQG4TE3bcsh:-KBsCwJSZSAsa6R4Ovuv:-1331902105) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/fae3d3d8421e8f8b76cbf72f8eec2b1bf8b57b33/td/templates/resources/language_detail.html#L105)):*
Couldn't you use else instead of specifying a default that way it doesn't have to check if the value is null twice? This way works also

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/473)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[td/templates/resources/language_detail.html, line 105 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/473#-KBsCwJRpBQG4TE3bcsh:-KBsEL7VZKzXTxAiKw9G:-547321263) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/fae3d3d8421e8f8b76cbf72f8eec2b1bf8b57b33/td/templates/resources/language_detail.html#L105)):*
I could. Fixing it now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/473)*

**Comment by vleong2332** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[td/templates/resources/language_detail.html, line 105 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/473#-KBsCwJRpBQG4TE3bcsh:-KBsGIuFQvqZxLHE-krx:-499146009) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/fae3d3d8421e8f8b76cbf72f8eec2b1bf8b57b33/td/templates/resources/language_detail.html#L105)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/473)*

**Comment by rbnswartz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[td/templates/resources/language_detail.html, line 105 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/473#-KBsCwJRpBQG4TE3bcsh:-KBsGuyGJ0UOwvrCsa5M:-1921560736) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/fae3d3d8421e8f8b76cbf72f8eec2b1bf8b57b33/td/templates/resources/language_detail.html#L105)):*
Looks good.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/473)*

**Pull request merged**
