### PR TITLE
Polished GL Tracker for Q1 Meeting (squashed)

### PR DESCRIPTION
**Pull request by vleong2332**
Try squashing several commits that are related into one.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/415)

### CODE REVIEW

**Comment by phillip-hopper** [comment]
Reviewed 1 of 64 files at r1.
Review status: 1 of 57 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415)*

**Comment by phillip-hopper** [comment]
Reviewed 62 of 64 files at r1, 3 of 3 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[td/gl_tracking/forms.py, line 33 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9XkBAL2bnMrluFN8jt:-K9XkBAMQ_Ps-Rv_VYaN:-188236275) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/gl_tracking/forms.py#L33)):*
I'm not sure what these are being used for, but a date format that uses a 2-digit year is ambiguous, for example: 10-11-12.

---

*[td/gl_tracking/migrations/0017_auto_20160121_1945.py, line 2 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9XlK4plOp6yvNox2Hr:-K9XlK4plOp6yvNox2Hs:-1813729794) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/gl_tracking/migrations/0017_auto_20160121_1945.py#L2)):*
I would give these files names that are more helpful.

---

*[td/templates/gl_tracking/dashboard.html, line 218 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9Xoh3g50HwM2H3eqpt:-K9Xoh3g50HwM2H3eqpu:1351867771) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/templates/gl_tracking/dashboard.html#L218)):*
You may want to trim the white-space from the end of lines, especially blank lines.

---

*[td/templates/gl_tracking/progress_update_modal_form.html, line 25 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9XukBmaSOsywmiJexB:-K9XukBmaSOsywmiJexC:1467817472) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/templates/gl_tracking/progress_update_modal_form.html#L25)):*
Indented with tabs instead of spaces

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[td/gl_tracking/forms.py, line 33 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9XkBAL2bnMrluFN8jt:-K9YGzIgRZx_XRM05G-R:-355648000) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/gl_tracking/forms.py#L33)):*
I was trying to give the user more freedom in how they type in a date, but I see your point. I'll remove the 2-digit year.

---

*[td/gl_tracking/migrations/0017_auto_20160121_1945.py, line 2 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9XlK4plOp6yvNox2Hr:-K9YHa4mKKI5JSSV0TRA:2108911715) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/gl_tracking/migrations/0017_auto_20160121_1945.py#L2)):*
are you talking about naming migration files?

---

*[td/templates/gl_tracking/dashboard.html, line 218 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9Xoh3g50HwM2H3eqpt:-K9YICEPRVTDbg3rcEuK:-2022360150) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/templates/gl_tracking/dashboard.html#L218)):*
Yeah, I should.  Too bad that flake8 doesn't catch errors in `.html` or `.js` I can start using a JS linter for these.

---

*[td/templates/gl_tracking/progress_update_modal_form.html, line 25 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9XukBmaSOsywmiJexB:-K9YISj0tDDwLiaPduW-:2011815916) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/templates/gl_tracking/progress_update_modal_form.html#L25)):*
Same thing as above. Because `flake8` doesn't catch these, I tend to be lazy and not check for these kind of things in non `.py` files. I'll remove the tabs.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[td/gl_tracking/migrations/0017_auto_20160121_1945.py, line 2 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9XlK4plOp6yvNox2Hr:-K9YJ_b-wE8gYXQXqzl6:-1974457810) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/gl_tracking/migrations/0017_auto_20160121_1945.py#L2)):*
How far do I need to go back renaming all these files? I can go forward with more meaningful names, but to go back and renaming, then re-pointing dependencies, seems too much of a trouble at this time.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415)*

**Comment by phillip-hopper** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[td/gl_tracking/migrations/0017_auto_20160121_1945.py, line 2 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9XlK4plOp6yvNox2Hr:-K9YiMBGYjNuxu1qC-4E:-991272544) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/gl_tracking/migrations/0017_auto_20160121_1945.py#L2)):*
I wouldn't worry about the past here.  If you decide to do that, it should be a separate pull request since it isn't related to this issue.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415)*

**Comment by vleong2332** [comment]
*[td/gl_tracking/migrations/0017_auto_20160121_1945.py, line 2 \[r3\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415#-K9XlK4plOp6yvNox2Hr:-K9YjgMlGvT45Gukbmfx:-770913915) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9f6a36f13b6c169e7627bee4b7a9ebf2bf65f2e6/td/gl_tracking/migrations/0017_auto_20160121_1945.py#L2)):*
Okay. I'll name migration files with meaningful name from now on.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/415)*

**Pull request merged**
