### PR TITLE
Temp solution to langnames using DB

### PR DESCRIPTION
**Pull request by vleong2332**
Store the JSON info in DB (currently run through management command) and when the request comes, return the data straight from DB.

Temporary solution for #456

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/466)

### CODE REVIEW

**Comment by rbnswartz** [comment]
Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[td/models.py, line 17 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/466#-KBnAffA4ROuFMIMAb-B:-KBnAffBBG9KoSCeM4te:-1124611185) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/dfc8b173f723246d352825d6f330387429372907/td/models.py#L17)):*
Created and modified look to be both time stamps. You can remove your save logic by using auto_now for the modified and auto_now_add for created.

https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.DateField

---

*[td/views.py, line 29 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/466#-KBnEcOBhEDSYqNBPglA:-KBnEcOBhEDSYqNBPglB:560913429) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/dfc8b173f723246d352825d6f330387429372907/td/views.py#L29)):*
Nice catch on the duplicate imports!

---

*[td/resources/management/commands/update_langnames_json.py, line 5 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/466#-KBnDa0RtDM2hTKFeyk2:-KBnDa0RtDM2hTKFeyk3:-1127620206) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/dfc8b173f723246d352825d6f330387429372907/td/resources/management/commands/update_langnames_json.py#L5)):*
I know this is valid but no one looking at it will know where in the world this is coming from. Should probably be an absolute import for clarity's purpose

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/466)*

**Comment by vleong2332** [comment]
*[td/models.py, line 17 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/466#-KBnAffA4ROuFMIMAb-B:-KBnW54UYgOcTBhbydah:1555097745) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/dfc8b173f723246d352825d6f330387429372907/td/models.py#L17)):*
There seems to be those who don't like `auto_now` and `auto_now_add`. Basically, it could raise issues during data migration. This is the SO post that presents the problem: http://stackoverflow.com/questions/1737017/django-auto-now-and-auto-now-add.

Though for our need, it seems to be okay with `now_auto` and `now_auto_add`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/466)*

**Comment by rbnswartz** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/466)*

**Comment by rbnswartz** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/466)*

**Comment by rbnswartz** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/466)*

**Pull request merged**
