### PR TITLE
Language Alternate Names and WA Region Assignment

### PR DESCRIPTION
**Pull request by vleong2332**
Resolves issue #430 - Assigning GL director to WA region

Resolves issue #56
   - Language alternate names are now included in `langnames.json`
   - Language alternate names are now shown on language list table and language detail page
   - Searching in language list also look for the alternate names

Resolves issue #377 - Spoken-in-countries are now displayed in language detail page

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/429)

### CODE REVIEW

**Comment by phillip-hopper** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[td/migrations/0014_merge.py, line 16 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjGaxIcqmXzRNAVYVR:-KAjGaxIcqmXzRNAVYVS:-1051008756) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/migrations/0014_merge.py#L16)):*
Does this file do anything?

---

*[td/migrations/0017_remove_language_alternate_name.py, line 19 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjHHzDtS_AnOcXuoHq:-KAjHHzDtS_AnOcXuoHr:-2115939999) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/migrations/0017_remove_language_alternate_name.py#L19)):*
Is there a reason you are adding fields and then removing them in the same pull request?

---

*[td/migrations/0019_gldirector_boolean_fields.py, line 3 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjHpaw9vid-oEgZlbn:-KAjHpaw9vid-oEgZlbo:-677098524) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/migrations/0019_gldirector_boolean_fields.py#L3)):*
The name of this file doesn't seem to go with what the code does.

---

*[td/models.py, line 194 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjI_tK7YWQLQRWR4S6:-KAjI_tLxt8QKPh8Sg69:2055768037) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/models.py#L194)):*
I think you may need to add a comment explaining the difference between `alt_name` and `alt_names`, and why we need both.

---

*[td/settings.py, line 264 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjJJn2eXhWtC3nzetP:-KAjJJn2eXhWtC3nzetQ:1373596374) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/settings.py#L264)):*
What is this used for?

---

*[td/templates/gl_tracking/region_assignment_modal_form.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjKD43gA38Lrmat6hl:-KAjKD43gA38Lrmat6hm:94351490) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templates/gl_tracking/region_assignment_modal_form.html#L1)):*
Every line in this file has trailing white space.

---

*[td/templates/resources/_empty_div_overlay.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjKVZLl-Z3Ps0GMjyC:-KAjKVZMlTgCyHS-p-SD:-2104749203) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templates/resources/_empty_div_overlay.html#L1)):*
The other html files are indented with spaces, but this one uses tabs.

---

*[td/templatetags/custom_filters.py, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjLBkGU5TkLciZWrFu:-KAjLBkGU5TkLciZWrFv:702990655) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templatetags/custom_filters.py#L1)):*
This file has trailing white space also.

---

*[td/templatetags/custom_filters.py, line 35 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjLWJP4KxQAJ9RyCTG:-KAjLWJQB024YutJuV1C:576551601) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templatetags/custom_filters.py#L35)):*
I would think this should return a word or phrase, maybe "unknown" or "not specified."

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[td/migrations/0014_merge.py, line 16 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjGaxIcqmXzRNAVYVR:-KAjdAMc6N6vUDcG4mGg:-1133937288) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/migrations/0014_merge.py#L16)):*
I'm not sure. It asked me to merge because it detects migration conflict. I'll look into this.

---

*[td/migrations/0017_remove_language_alternate_name.py, line 19 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjHHzDtS_AnOcXuoHq:-KAjeOEs-_xtLBwHtTwi:-1312728743) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/migrations/0017_remove_language_alternate_name.py#L19)):*
I added and removed fields because the solution to implementing language alternate names evolved a couple times. Sometimes, removing or changing the field type also require more than one migration file. Personally, I like to see these "trials" migration squashed into the final solution, but I'm not really good with migration things and tend to break things when messing with it.  Django doc says I don't need to worry about migration files unless they go up to hundred files. I'm happy to learn the best practices on this that can be applied deployment and to my local db.

---

*[td/migrations/0019_gldirector_boolean_fields.py, line 3 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjHpaw9vid-oEgZlbn:-KAjgWYBOZ4kjZfJ7uSS:946289247) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/migrations/0019_gldirector_boolean_fields.py#L3)):*
That's weird. I thought I added 2 boolean fields along with this constraint. I'll check into this. I could be missing the last migration.

---

*[td/models.py, line 194 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjI_tK7YWQLQRWR4S6:-KAjgkZGD9BLwOAhRRdL:-1504763431) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/models.py#L194)):*
Good idea.

---

*[td/settings.py, line 264 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjJJn2eXhWtC3nzetP:-KAjihg2M_NH23kuqI7W:2112884940) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/settings.py#L264)):*
The key to consume Joshua Project API. We're displaying the data from JP in the language detail page.

---

*[td/templates/gl_tracking/region_assignment_modal_form.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjKD43gA38Lrmat6hl:-KAjjN3HxyiTNqKm6B-7:-1394943414) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templates/gl_tracking/region_assignment_modal_form.html#L1)):*
Weird. I'm not seeing it in my text editor. We'll see if this still comes up in the next revision

---

*[td/templates/resources/_empty_div_overlay.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjKVZLl-Z3Ps0GMjyC:-KAjjjvfuY6PbEOypVMc:-672321192) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templates/resources/_empty_div_overlay.html#L1)):*
Sure enough.

---

*[td/templatetags/custom_filters.py, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjLBkGU5TkLciZWrFu:-KAjjpqXcadKxzt4CWKc:-907550491) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templatetags/custom_filters.py#L1)):*
I don't see this in my text editor also.

---

*[td/templatetags/custom_filters.py, line 35 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjLWJP4KxQAJ9RyCTG:-KAjjvXsj7nwf5gB3nV1:800285645) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templatetags/custom_filters.py#L35)):*
I'm debating this myself. I'm trying to be consistent in displaying empty field as a dash (-) because, from UX perspective, it's super easy to recognize the absence of a data entry by, well, an empty space (as opposed to words/phrases). In this case, I go with a dash (which is much simpler than a word or even "N/A") to distinguish between a definite "there is no entry for this field" and a vague "is it empty or is the data misplaced/missed/skipped/etc.?".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[td/migrations/0019_gldirector_boolean_fields.py, line 3 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjHpaw9vid-oEgZlbn:-KAjrJhnZoSgvOHOporm:516317691) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/migrations/0019_gldirector_boolean_fields.py#L3)):*
Ah! I know. When running `makemigrations` I assign a name `-n <name>` but it assigns the name for all the created migration file, even if it's on a different app, like in this case. I think I can change the name without much repercussion here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[td/migrations/0017_remove_language_alternate_name.py, line 19 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjHHzDtS_AnOcXuoHq:-KAk01H4UmDQtE5evr6_:-778429460) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/migrations/0017_remove_language_alternate_name.py#L19)):*
This is what I referred to https://docs.djangoproject.com/en/1.9/topics/migrations/#squashing-migrations

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Comment by phillip-hopper** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[td/templates/gl_tracking/region_assignment_modal_form.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjKD43gA38Lrmat6hl:-KAk5SNtg5tRxhe_Ia3G:1492203879) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templates/gl_tracking/region_assignment_modal_form.html#L1)):*
Still there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Comment by vleong2332** [comment]
*[td/templates/gl_tracking/region_assignment_modal_form.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjKD43gA38Lrmat6hl:-KAk9b_90veah0PjLlqU:1790600792) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templates/gl_tracking/region_assignment_modal_form.html#L1)):*
I have no idea why it's showing here. It doesn't even show on Github. I'd call this one a glitch.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Comment by phillip-hopper** [comment]
Review status: 35 of 36 files reviewed at latest revision, 3 unresolved discussions.

---

*[td/templates/gl_tracking/region_assignment_modal_form.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjKD43gA38Lrmat6hl:-KAkOwgLDezyaGS-BWlk:1151374367) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templates/gl_tracking/region_assignment_modal_form.html#L1)):*
I checked, and the issue is some of the files were checked in with Windows line-endings `\r\n`.  Can you set you git client to always push Unix/Linux line endings?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Comment by vleong2332** [comment]
*[td/templates/gl_tracking/region_assignment_modal_form.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429#-KAjKD43gA38Lrmat6hl:-KAkeYwpwLrvL4UFu7kD:-1819001473) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/181ed3e9558138d09f3413e70899abd6a7235cf0/td/templates/gl_tracking/region_assignment_modal_form.html#L1)):*
I think I fixed this. Doing what's recommended here: https://help.github.com/articles/dealing-with-line-endings/#platform-linux

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Comment by vleong2332** [comment]
Reviewed 8 of 9 files at r5, 1 of 1 files at r6, 11 of 11 files at r7.
Review status: 41 of 48 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Comment by vleong2332** [comment]
Reviewed 7 of 41 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/429)*

**Pull request merged**
