### PR TITLE
Temporary language

### PR DESCRIPTION
**Pull request by vleong2332**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/516)

### CODE REVIEW

**Comment by phillip-hopper** [comment]
Reviewed 18 of 41 files at r1, 5 of 12 files at r3, 3 of 7 files at r4, 9 of 13 files at r5, 15 of 17 files at r7.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[static/src/js/language_list.js, line 10 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYFUwjdHRj-2kM4mKX:-KEYFUwjdHRj-2kM4mKY:-1110588695) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/static/src/js/language_list.js#L10)):*
In `homepage.js` jQuery is used, but not here. Why?

---

*[static/src/js/language_list.js, line 12 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYFHWJ716u8u9cTfU4:-KEYFHWK0VCFfhwMdXjv:1385710410) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/static/src/js/language_list.js#L12)):*
Why not use a simple `if` statement here, especially since the value is not being assigned?

---

*[td/views_ajax.py, line 0 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYJXJxX21h6URHgauI:-KEYJXJyd4pjElqe0SSz:746274922) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/views_ajax.py#L0)):*
Why is this file included? It looks empty.

---

*[td/publishing/models.py, line 359 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYJxQ1jf1lfJr8gTIi:-KEYJxQ1jf1lfJr8gTIj:-739508283) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/publishing/models.py#L359)):*
Why are we allowing the language to be null?

---

*[td/templates/resources/language_modal_form.html, line 35 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYLotMeJW_ZDv9a5WH:-KEYLotN0CjsiDhMmex6:-1476032691) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/templates/resources/language_modal_form.html#L35)):*
You don't need `document` here, it's redundant. `$().ready(...` works.

---

*[td/templates/resources/email/templanguage_notify_plain.html, line 1 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYN4c4XaVrZBn4SPCL:-KEYN4c4XaVrZBn4SPCM:1572831502) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/templates/resources/email/templanguage_notify_plain.html#L1)):*
Since this file contains no HTML, would it be more appropriate to call it `.txt`?

---

*[td/tracking/urls.py, line 24 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYNbzDDPD7CJ_KqFFb:-KEYNbzEAKzChEuqSpzf:820281786) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/50e6e924394a2498c2912bd2b89db7ca3621abd1/td/tracking/urls.py#L24)):*
Was this intentional since the only change is removing a blank line? I the only change is white-space, you should just revert it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[static/src/js/language_list.js, line 10 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYFUwjdHRj-2kM4mKX:-KEaylBG-O-7bkoxxxhZ:1813485565) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/static/src/js/language_list.js#L10)):*
The only reason is that I'm trying to write as many pure JavaScript as possible and using jQuery only for assistance. That way, I hope to learn the language more than the library.

---

*[static/src/js/language_list.js, line 12 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYFHWJ716u8u9cTfU4:-KEaz5w2sL4HvLmydCdr:597664247) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/static/src/js/language_list.js#L12)):*
You're right. The ternary operator is not the best for this case.

---

*[td/publishing/models.py, line 359 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYJxQ1jf1lfJr8gTIi:-KEazVhlFT04WWcblFdt:2091421783) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/publishing/models.py#L359)):*
Hmm. I think this is a left over from a troubleshooting session. I'll remove this back to default (CASCADE).

---

*[td/templates/resources/language_modal_form.html, line 35 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYLotMeJW_ZDv9a5WH:-KEaztp60-n3c64HS1fp:677251276) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/templates/resources/language_modal_form.html#L35)):*
Yes.

---

*[td/templates/resources/email/templanguage_notify_plain.html, line 1 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYN4c4XaVrZBn4SPCL:-KEazxbBFaHA55PtXDl7:-118469900) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/templates/resources/email/templanguage_notify_plain.html#L1)):*
That makes sense. I was following an example that's already there for Publish Request notification.

---

*[td/tracking/urls.py, line 24 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYNbzDDPD7CJ_KqFFb:-KEayX19A9Md43ohceZq:1228798151) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/50e6e924394a2498c2912bd2b89db7ca3621abd1/td/tracking/urls.py#L24)):*
No, it must have been a mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516)*

**Comment by vleong2332** [comment]
*[td/views_ajax.py, line  \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYJXJxX21h6URHgauI:-KEb0LFCISv0fYiElEtt:1116821038) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/views_ajax.py#L)):*
Leftover. Will remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516)*

**Comment by vleong2332** [comment]
*[td/templates/resources/email/templanguage_notify_plain.html, line 1 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYN4c4XaVrZBn4SPCL:-KEb0P0gIuTNHC-MnuvJ:531436665) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/templates/resources/email/templanguage_notify_plain.html#L1)):*
Actually, would the abosluteuri tag and the variables be rendered correctly by the django template?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516)*

**Comment by phillip-hopper** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r8, 2 of 3 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[td/templates/resources/email/templanguage_notify_plain.html, line 1 \[r7\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-KEYN4c4XaVrZBn4SPCL:-KEb5aEX8OJcr6NfKcmg:-543608763) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1593fb101d5dbf5c21f1ca39e6fcdf73fda3dfc8/td/templates/resources/email/templanguage_notify_plain.html#L1)):*
They should be, unless django is hard-coded to look for a .html extension.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/516#-:-KEb6aYCZT8QzoJlX3kU:1417088721)*

**Pull request merged**
