### PR TITLE
Bootstrap datepicker for tracking and gl_tracking forms

### LINKED ISSUE #331: td.tracking: Use a better date picker
Use bootstrap datepicker for:
- [x] Progress update form
- [x] Charter forms
- [x] Event forms

### PR DESCRIPTION
**Pull request by vleong2332**
Resolves #331 

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/441)

### CODE REVIEW

**Comment by rbnswartz** [comment]
Reviewed 11 of 13 files at r1.
Review status: 11 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[static/src/js/main.js, line 79 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNga3jjkmROq6UwdKN:-KBNga3jjkmROq6UwdKO:163052406) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/7d0ae94bf1eeb633417ec2ae7a14f891d5f7f4fb/static/src/js/main.js#L79)):*
Is this needed since we made the change to the format in the datepicker?

---

*[td/fields.py, line 26 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNeuKWPP05bUihYkbW:-KBNeuKWPP05bUihYkbX:-217412238) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/7d0ae94bf1eeb633417ec2ae7a14f891d5f7f4fb/td/fields.py#L26)):*
Should probably should change this to "Text field to search for a language" minor though since I don't think many users are going to actually see that string.

---

*[td/templates/_scripts.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNgrv1PB5hzLX7ze1G:-KBNgrv2GytoCtM0hqqx:1844346869) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/728e21318172fc01a0d9f83b7f9c641d27e49f2c/td/templates/_scripts.html#L1)):*
I take it this is just due to a regeneration of the scripts due to the changes that you made

---

*[td/templates/_styles.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNgzZ3FrcwXkAWWio7:-KBNgzZ4dsyY5BvumyXj:-2073021532) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/728e21318172fc01a0d9f83b7f9c641d27e49f2c/td/templates/_styles.html#L1)):*
Same as above

---

*[td/tracking/forms.py, line 78 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNfmJ2FlDB7OdQGNld:-KBNfmJ3MYjppUO0FjkN:-742370509) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/728e21318172fc01a0d9f83b7f9c641d27e49f2c/td/tracking/forms.py#L78)):*
You seemed to have removed a whole bunch of comments. Was that on purpose?

---

*[td/tracking/views.py, line 175 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNgHuI230h-V3I4YR2:-KBNgHuJJR22N7b6pUe_:-302802293) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/728e21318172fc01a0d9f83b7f9c641d27e49f2c/td/tracking/views.py#L175)):*
Again removing comments I don't know if this was intended or not. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441)*

**Comment by vleong2332** [comment]
Review status: 11 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[static/src/js/main.js, line 79 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNga3jjkmROq6UwdKN:-KBNpxAkmjdUvEN5QYwI:-1446193356) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/7d0ae94bf1eeb633417ec2ae7a14f891d5f7f4fb/static/src/js/main.js#L79)):*
I'm checking to see if we just need to provide the right markup for BSDateField to initialize it.

---

*[td/templates/_scripts.html, line 1 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNgrv1PB5hzLX7ze1G:-KBNq9nW4mMOcXxmtA4z:-536025735) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/728e21318172fc01a0d9f83b7f9c641d27e49f2c/td/templates/_scripts.html#L1)):*
Yes. It's changed whenever you run `npm run bulid`

---

*[td/tracking/forms.py, line 78 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNfmJ2FlDB7OdQGNld:-KBNqFj0YD75m2dqDGwQ:286064506) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/728e21318172fc01a0d9f83b7f9c641d27e49f2c/td/tracking/forms.py#L78)):*
Yes. I feel like the comments were not useful and rather obvious. They were made earlier on in my learning path. Do you think that's not the case?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441)*

**Comment by rbnswartz** [comment]
Review status: 11 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[td/tracking/forms.py, line 78 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNfmJ2FlDB7OdQGNld:-KBNrufdI50WJ8k63FbE:95360847) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/728e21318172fc01a0d9f83b7f9c641d27e49f2c/td/tracking/forms.py#L78)):*
Yeah they are pretty self explanatory. You can never have too many comments though. Just wanted to make sure it wasn't a bad merge that removed them. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441)*

**Comment by phillip-hopper** [comment]
Reviewed 1 of 13 files at r2, 18 of 18 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[td/fields.py, line 19 \[r4\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KCGFMjvkL_oqdQObocI:-KCGFMjwtlI-MnAVMsEv:776553471) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/d46568ddd4a3e55b728687b7cac52e5e1d69e98f/td/fields.py#L19)):*
Since this is for international consumption, this is probably not the best format.  Perhaps something that's not ambiguous, like `2016-03-07` or `07 MAR 2016`.

---

*[td/tracking/views.py, line 175 \[r4\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KCGHHDhz2L5dMPrrIB4:-KCGHHDhz2L5dMPrrIB5:-1773286960) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/e22dafe3e05f9dd87cc08a968a10e042ede70283/td/tracking/views.py#L175)):*
I agree that comments should not be removed unless they don't apply any more.  Apparently someone thought they were a good idea.  What seems obvious to you may not be obvious to someone else.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441)*

**Comment by vleong2332** [comment]
Reviewed 7 of 18 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[td/fields.py, line 26 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNeuKWPP05bUihYkbW:-KCGRYm9H84JnorCsTcs:-499146009) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/7d0ae94bf1eeb633417ec2ae7a14f891d5f7f4fb/td/fields.py#L26)):*
Done.

---

*[td/fields.py, line 19 \[r4\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KCGFMjvkL_oqdQObocI:-KCRGaxaXWYJRV2HQf6E:1733658307) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/d46568ddd4a3e55b728687b7cac52e5e1d69e98f/td/fields.py#L19)):*
I don't think ambiguity will be a problem here because:
1. There's gonna be a placeholder that indicate the same format when the info is being entered. 
2. Users will most likely use the datepicker, which is not ambiguous at all
3. The data displayed on the table will not be ambiguous
4. This is mainly to tell the widget how to display the existing data (if any) on edit/update view so that it plays nice with the datepicker.

---

*[td/tracking/views.py, line 175 \[r4\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KCGHHDhz2L5dMPrrIB4:-KCRHz1uRNoSdMpF7pcw:1866441063) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/e22dafe3e05f9dd87cc08a968a10e042ede70283/td/tracking/views.py#L175)):*
The comments were somewhere along the line of "Overridden to add custom logic". I wrote it when I was new to Python's object-oriented model and I wrote it on top of *every* overridden function. If you guys think that'd be helpful, I'll be happy to put it all back in.

---

*[static/src/js/main.js, line 79 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-KBNga3jjkmROq6UwdKN:-KCRIjGKFgqu6FXWb7A1:-539301458) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/7d0ae94bf1eeb633417ec2ae7a14f891d5f7f4fb/static/src/js/main.js#L79)):*
We can initialize it with the data-attribute.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441)*

**Comment by phillip-hopper** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/441#-:-KCRM9NWJic5KU0IMOS7:1417088721)*

**Pull request merged**
