### PR TITLE
WA Region List and Detail

### PR DESCRIPTION
**Pull request by vleong2332**
Reuben's initial work:
 - wa_region to country
 - wa_region detail view
 - wa_region list view
 - countries

Vicky's addition:
 - Displayed translation projects under WA Region detail that belongs to that region
 - Displayed an extra WA Region column for project list
 - Wrote management command to import country-to-WA-region mapping
 - Wrote management command to fill_in_language_wa_region relation
 - Showed countries under the region
 - Show GL directors and helpers for the region
 - Implement tabs for info, projects, and countries view

Cleanup

---
This change is [Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/489)

### CODE REVIEW

**Comment by phillip-hopper** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[td/urls.py, line 27 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489#-KCWLCG0hW571vibWeuY:-KCWLCG0hW571vibWeuZ:-2123390074) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/8eba6834733d10c08f29caf52ad2be48425d86b9/td/urls.py#L27)):*
This change is probably not necessary.

---

*[td/migrations/0021_added_wa_region_to_country.py, line 19 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489#-KCWMgk7bedT9O6Qo3yc:-KCWMgk7bedT9O6Qo3yd:-1292718350) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/8eba6834733d10c08f29caf52ad2be48425d86b9/td/migrations/0021_added_wa_region_to_country.py#L19)):*
Are you sure you want to cascade deletes?

---

*[td/templates/site_base.html, line 156 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489#-KCWOxZEh_8D7vJiUxYN:-KCWOxZEh_8D7vJiUxYO:507299270) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/8eba6834733d10c08f29caf52ad2be48425d86b9/td/templates/site_base.html#L156)):*
This condition is the same as the one above it, they should be combined into one block.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[td/urls.py, line 27 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489#-KCWLCG0hW571vibWeuY:-KCWxDfQFwhftYgOqzBw:-1002003061) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/8eba6834733d10c08f29caf52ad2be48425d86b9/td/urls.py#L27)):*
I don't see the change. What was it?

---

*[td/migrations/0021_added_wa_region_to_country.py, line 19 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489#-KCWMgk7bedT9O6Qo3yc:-KCWxb91QsX2rhppGaE6:-1745247732) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/8eba6834733d10c08f29caf52ad2be48425d86b9/td/migrations/0021_added_wa_region_to_country.py#L19)):*
Nope. Most likely an oversight.

---

*[td/templates/site_base.html, line 156 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489#-KCWOxZEh_8D7vJiUxYN:-KCWyWMLhNkzTTT3wnDd:-1834867264) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/8eba6834733d10c08f29caf52ad2be48425d86b9/td/templates/site_base.html#L156)):*
Thanks.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[td/templates/site_base.html, line 156 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489#-KCWOxZEh_8D7vJiUxYN:-KCWyq9PA490IYtTfbSl:561995786) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/8eba6834733d10c08f29caf52ad2be48425d86b9/td/templates/site_base.html#L156)):*
Actually, thanks for catching this. I meant to move one of the list in between the `if` statements.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489)*

**Comment by phillip-hopper** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[td/urls.py, line 27 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489#-KCWLCG0hW571vibWeuY:-KCX0vJSygV3fS6Z17CO:1634681456) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/8eba6834733d10c08f29caf52ad2be48425d86b9/td/urls.py#L27)):*
A comma was added after 'languages_autocomplete'.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/489)*

**Pull request merged**
