### PR TITLE
Events information

### PR DESCRIPTION
**Pull request by vleong2332**
Create Events dashboard that contains event total, event-count form, event-count table, and event list "components".

Event-count form and table are also embedded in WA Region, Country, and Language detail page.

Resolves: #555, #556, #560, #557, #558, #563

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/590)

### CODE REVIEW

**Comment by vleong2332** [comment]
@rbnswartz, do you know why travis and coverall are not running for this PR?

**Comment by rbnswartz** [comment]
Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[td/templates/resources/_language_list.html, line 18 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISnf8pTU4AVwXV0lfP:-KISnf8qNjdt2HRGctN_:-52425678) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/templates/resources/_language_list.html#L18)):*
> ```HTML
>             <tr>
>                 <td>
>                     <a class="btn btn-default btn-xs" href="{% url "language_edit" language.pk %}"><i class="fa fa-fw fa-pencil"></i> Edit</a>
> ```

Is this now behind the login wall? Because the edit button is showing to everyone.

---

*[td/templates/resources/country_detail.html, line 11 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISo4J6GUP28SwnUsK1:-KISo4J6GUP28SwnUsK2:-1646064212) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/1b3188430e006c306637b5df9f7057a2279c3a9e/td/templates/resources/country_detail.html#L11)):*
> ```HTML
> <h1>
>   {{ country.name }}
>     {% if user.is_authenticated %}
> ```

Again. Is this now behind the login wall?

---

*[td/templates/resources/country_detail.html, line 42 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISoTuKInn9W2KAQTNi:-KISoTuLP1ykR-dYg6Fn:806570130) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/templates/resources/country_detail.html#L42)):*
> ```HTML
>                     <tbody>
>                         <tr><th class="col-md-2">Code</th><td>{{ country.code|default:"_" }}</td><tr>
>                         <tr><th>Population</th><td>{{ gl_directors|join:", "|default:"-" }}</td></tr>
> ```

This doesn't seem to match up. Population should be the names of the gl directors joined?

---

*[td/templates/resources/country_list.html, line 8 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISpcBzevrvak1YN2wZ:-KISpcBzevrvak1YN2w_:1713022532) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/templates/resources/country_list.html#L8)):*
> ```HTML
>     <h2>Countries</h2>
>     <hr />
>     
> ```

Any time there is a todo I must ask should this be done now or later?

---

*[td/templatetags/show_event_count_form.py, line 14 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISrALC7UVvjqhygBU_:-KISrALC7UVvjqhygBUa:-633969171) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/templatetags/show_event_count_form.py#L14)):*
> ```Python
>     # print "====================="
>     # print "context:", context
>     # print "kwargs:", kwargs
> ```

Commented out code should probably be removed

---

*[td/tests/test_models.py, line 263 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISrObCvUbND39gB2D-:-KISrObCvUbND39gB2D0:-1383583404) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tests/test_models.py#L263)):*
> ```Python
>     def test_get_absolute_url(self):
>         """get_absolute_url of a language should return the link to its detail page"""
>         self.assertEqual(self.lang.get_absolute_url(), reverse("language_detail", kwargs={"pk": 999}))
> ```

You could just use reverse("language_detail", kwargs={"pk": self.lang.pk}) and you wouldn't have to initialize the pk

---

*[td/tests/test_models.py, line 303 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISrguVkOXO_WaX3lLx:-KISrguWSziKfqGSAltE:-1396893667) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tests/test_models.py#L303)):*
> ```Python
> 
>     def setUp(self):
>         self.country, _ = Country.objects.get_or_create(pk=999, code="go", name="Gondor")
> ```

This could cause unexpected test results in the future if there already exists a Country with the pk 999. This works currently but if another test case is added to this it could have issues. Safer would be just to let it come up with its own pk and then use self.country.pk to reference it.

---

*[td/tests/test_models.py, line 313 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISsMahQwcey9xiETeq:-KISsMaiIbHzLWVBYb_k:-2073021532) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tests/test_models.py#L313)):*
> ```Python
> 
>     def setUp(self):
>         self.wa_region, _ = WARegion.objects.get_or_create(pk=999, name="Middle Earth", slug="middleearth")
> ```

Same as above

---

*[td/tests/test_utils.py, line 9 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISsQLQ99iqgRNmdxZ1:-KISsQLQ99iqgRNmdxZ2:-412677469) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tests/test_utils.py#L9)):*
> ```Python
> 
>     def test_non_tuple_type(self):
>         t = "Hobbits"
> ```

LOL very nice.

---

*[td/tests/tracking/test_views.py, line 1349 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KIT7HU9DJvL2UBikFBf:-KIT7HUAFzcVypsFA_at:1824913676) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tests/tracking/test_views.py#L1349)):*
> ```Python
> 
>     def setUp(self):
>         pass
> ```

If setup isn't needed why not just remove it instead of passing?

---

*[td/tracking/urls.py, line 54 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KIT7QakniSKjTxmmv6e:-KIT7QalfwaZrh9ZzFi4:-69770729) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tracking/urls.py#L54)):*
> ```Python
>     # Ajax
>     url(r"^ajax/charter_events/(?P<pk>\d+)/$", AjaxCharterEventsListView.as_view(), name="ajax_charter_events"),
>     # TODO: rework like urls
> ```

Has this been done or is it still needed?

---

*[td/tracking/views.py, line 128 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KIT84_H5ubWEimcSmHq:-KIT84_H5ubWEimcSmHr:-1351960896) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tracking/views.py#L128)):*
> ```Python
>     def filtered_data(self):
>         return self.queryset\
>             .filter(reduce(operator.or_, [Q(x) for x in self.filter_predicates]))\
> ```

It looks like you limited the searching to exact matches instead of using contains. Was that intended?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[td/templates/resources/country_list.html, line 8 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISpcBzevrvak1YN2wZ:-KIThhGBsVf8K1d_T3m2:-1601583232) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/templates/resources/country_list.html#L8)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Any time there is a todo I must ask should this be done now or later?
</details>
I always use TODO to mark what needs to be done later or in the future. Things that needs to be done now are already done and kept tracked on my personal list.

---

*[td/tracking/urls.py, line 54 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KIT7QakniSKjTxmmv6e:-KITjhO2KtQEDPJ2QbD8:1158838769) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tracking/urls.py#L54)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Has this been done or is it still needed?
</details>
Still needed and worth its own PR.

---

*[td/tracking/views.py, line 128 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KIT84_H5ubWEimcSmHq:-KITkn1oGEfD-fXnRTsb:-167262835) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tracking/views.py#L128)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> It looks like you limited the searching to exact matches instead of using contains. Was that intended?
</details>
I'm not sure how it would limit to exact matches.`self.filter_predicates` returns a list of `{0}_icontains.format(field)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590)*

**Comment by rbnswartz** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[td/templates/resources/country_list.html, line 8 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISpcBzevrvak1YN2wZ:-KIU3ooLBsblAx-GlD9x:-25251876) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/templates/resources/country_list.html#L8)):*
<details><summary><i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>
> I always use TODO to mark what needs to be done later or in the future. Things that needs to be done now are already done and kept tracked on my personal list.
</details>
Shouldn't we just create issues for that in github instead of a comment in the code? That way we have a way of tracking it beyond doing a search for the word todo.

---

*[td/tracking/urls.py, line 54 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KIT7QakniSKjTxmmv6e:-KIU4eR_8mqMsRZtTXui:-656093578) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tracking/urls.py#L54)):*
<details><summary><i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>
> Still needed and worth its own PR.
</details>
Again should probably be in a issue so it can be tracked (same as above) but I'm good either way

---

*[td/tracking/views.py, line 128 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KIT84_H5ubWEimcSmHq:-KIU4UKpYqDztKNIOK3E:1619550711) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tracking/views.py#L128)):*
<details><summary><i>Previously, vleong2332 (Vicky Leong) wrote…</i></summary>
> I'm not sure how it would limit to exact matches.`self.filter_predicates` returns a list of `{0}_icontains.format(field)`
</details>
Okay good. Just wanted to make sure we weren't eliminating already existing functionality that the users will most likely need.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590)*

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[td/templates/resources/country_list.html, line 8 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KISpcBzevrvak1YN2wZ:-KIUILwREjs1rJEB4oF_:628534802) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/templates/resources/country_list.html#L8)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Shouldn't we just create issues for that in github instead of a comment in the code? That way we have a way of tracking it beyond doing a search for the word todo.
</details>
Issue created.

---

*[td/tracking/urls.py, line 54 \[r1\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590#-KIT7QakniSKjTxmmv6e:-KIUInCGcZ2leSHb8BC4:1405748636) ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/b44cd1a89e89fec31157f678426663edd7782e28/td/tracking/urls.py#L54)):*
<details><summary><i>Previously, rbnswartz (Reuben Swartz) wrote…</i></summary>
> Again should probably be in a issue so it can be tracked (same as above) but I'm good either way
</details>
Issue created

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/590)*

**Comment by rbnswartz** [comment]
Good to go @vleong2332 .

**Pull request merged**
