### PR TITLE
Multicharter event form && Prod error fix

### PR DESCRIPTION
**Pull request by vleong2332**
[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/274)

### CODE REVIEW

**Comment by cdaield** [comment]
Reviewed 17 of 29 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[td/tracking/templates/tracking/charter_form.html, line 48 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JB0bwmfre3rYEY67J)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/templates/tracking/charter_form.html#L48)):</sup>
Small typo: missing a space in 'languagefor'


---

<sup>**[td/tracking/views.py, line 519 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JH7RKXplLXFdyLVr5)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/views.py#L519)):</sup>
Debug code?


---

<sup>**[td/tracking/views.py, line 577 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JHTra4kNkGBPxiqre)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/views.py#L577)):</sup>
Why are these recipients hard-coded?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274)

**Comment by vleong2332** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[td/tracking/templates/tracking/charter_form.html, line 48 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JB0bwmfre3rYEY67J)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/templates/tracking/charter_form.html#L48)):</sup>
Space removed.


---

<sup>**[td/tracking/views.py, line 519 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JH7RKXplLXFdyLVr5)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/views.py#L519)):</sup>
Right. That's a debug code.


---

<sup>**[td/tracking/views.py, line 577 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JHTra4kNkGBPxiqre)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/views.py#L577)):</sup>
Right. That's a debug code.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274)

**Comment by vleong2332** [comment]
Review status: 28 of 30 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[td/tracking/templates/tracking/charter_form.html, line 48 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JB0bwmfre3rYEY67J)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/templates/tracking/charter_form.html#L48)):</sup>
Done.


---

<sup>**[td/tracking/views.py, line 519 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JH7RKXplLXFdyLVr5)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/views.py#L519)):</sup>
Done.


---

<sup>**[td/tracking/views.py, line 577 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JHTra4kNkGBPxiqre)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/views.py#L577)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274)

**Comment by vleong2332** [comment]
Review status: 28 of 30 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[td/tracking/views.py, line 577 \[r2\]](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274#-K2JHTra4kNkGBPxiqre)** ([raw file](https://github.com/unfoldingword-dev/translationdatabaseweb/blob/9c18d39943b0f58589aad904a49e685f6cc56ce8/td/tracking/views.py#L577)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274)

**Comment by cdaield** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/unfoldingword-dev/translationdatabaseweb/274)

**Comment by cdaield** [comment]
:shipit:

**Pull request merged**
